# -*- coding: utf-8 -*-
"""Program-2 Operators in Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jXMSscsH9zljyXbz256r8t_bmyt8vebj

## **Aim: Write a program to implement all operators in python.**
"""

a=8
b=10
print(a)
print(b)

"""Arithmatic Operators"""

add = a+b
sub = b-a
mult = a*b
divfloat = b/a
divfloor = b//a
mod = b%a

print(" \n Results \n")
print(add)
print(sub)
print(mult)
print(divfloat)
print(divfloor)
print(mod)

"""Relational operators"""

a=8
b=10
print(a)
print(b)

a>b
a<b
a==b
a!=b
a>=b
a<=b

"""Logical operators"""

a=True
b=False
print(a)
print(b)
a and b
a or b
not a

"""Bitwise operators"""

a=8
b=10
print(a)
print(b)
print(a & b)
print(a | b)
print(~a)
print(a ^ b)
print(a >> 2)
print(a << 2)

